#!/bin/bash
###############################################################################
# connect-local-gpu.sh - Configure remote Ollama connection
#
# This script configures the server to connect to a local GPU machine
# running Ollama for LLM inference.
#
# Usage: ./connect-local-gpu.sh <gpu-machine-ip> [port]
###############################################################################

set -euo pipefail

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
DEFAULT_PORT=11434
CONFIG_FILE="/etc/environment"
PROFILE_FILE="/etc/profile.d/ollama-remote.sh"

# Logging functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

error_exit() {
    log_error "$1"
    exit 1
}

# Usage information
usage() {
    cat << EOF
Usage: $0 <gpu-machine-ip> [port]

Configure connection to remote Ollama instance on GPU machine.

Arguments:
  gpu-machine-ip    IP address of the machine with GPU running Ollama
  port              Ollama port (default: $DEFAULT_PORT)

Examples:
  $0 192.168.1.100
  $0 192.168.1.100 11434
  $0 localhost       # Use local Ollama

To disconnect and use local Ollama:
  $0 localhost

GPU Machine Setup:
  On your GPU machine, ensure Ollama is exposed to network:

  echo 'OLLAMA_HOST=0.0.0.0:11434' | sudo tee -a /etc/environment
  sudo systemctl restart ollama
EOF
    exit 1
}

# Check if running as root for system-wide config
check_permissions() {
    if [[ $EUID -ne 0 ]] && [[ "$1" == "system" ]]; then
        error_exit "System-wide configuration requires root privileges (use sudo)"
    fi
}

# Validate IP address
validate_ip() {
    local ip="$1"

    if [ "$ip" = "localhost" ] || [ "$ip" = "127.0.0.1" ]; then
        return 0
    fi

    if [[ ! "$ip" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        error_exit "Invalid IP address format: $ip"
    fi
}

# Test connection to Ollama
test_connection() {
    local host="$1"
    local port="$2"
    local url="http://$host:$port/api/tags"

    log_step "Testing connection to $url..."

    if curl -f -s -m 5 "$url" > /dev/null; then
        log_info "✓ Connection successful!"

        # List available models
        log_info "Available models:"
        curl -s "$url" | grep -o '"name":"[^"]*"' | cut -d'"' -f4 | sed 's/^/  - /' || log_warn "Could not list models"
        return 0
    else
        log_error "✗ Connection failed!"
        log_error "Make sure Ollama is running on $host:$port and is accessible"
        return 1
    fi
}

# Configure system-wide Ollama host
configure_system_wide() {
    local ollama_host="$1"

    log_step "Configuring system-wide Ollama connection..."

    # Create profile script
    cat > "$PROFILE_FILE" << EOF
# Ollama Remote Configuration
# Generated by connect-local-gpu.sh on $(date)
export OLLAMA_HOST=$ollama_host
EOF

    chmod 644 "$PROFILE_FILE"

    # Update /etc/environment
    if grep -q "OLLAMA_HOST" "$CONFIG_FILE"; then
        sed -i "s|OLLAMA_HOST=.*|OLLAMA_HOST=$ollama_host|" "$CONFIG_FILE"
        log_info "Updated existing OLLAMA_HOST in $CONFIG_FILE"
    else
        echo "OLLAMA_HOST=$ollama_host" >> "$CONFIG_FILE"
        log_info "Added OLLAMA_HOST to $CONFIG_FILE"
    fi

    log_info "System-wide configuration updated"
}

# Configure user-level Ollama host
configure_user_level() {
    local ollama_host="$1"
    local actual_user="${SUDO_USER:-$USER}"
    local user_home=$(eval echo "~$actual_user")
    local bashrc="$user_home/.bashrc"

    log_step "Configuring user-level Ollama connection for $actual_user..."

    # Update .bashrc
    if grep -q "export OLLAMA_HOST" "$bashrc"; then
        sed -i "s|export OLLAMA_HOST=.*|export OLLAMA_HOST=$ollama_host|" "$bashrc"
        log_info "Updated existing OLLAMA_HOST in $bashrc"
    else
        echo "" >> "$bashrc"
        echo "# Ollama Remote Configuration" >> "$bashrc"
        echo "export OLLAMA_HOST=$ollama_host" >> "$bashrc"
        log_info "Added OLLAMA_HOST to $bashrc"
    fi

    # Set for current session
    export OLLAMA_HOST="$ollama_host"
}

# Create helper script for easy testing
create_test_script() {
    local ollama_host="$1"

    log_step "Creating test script..."

    cat > /usr/local/bin/ollama-test << EOF
#!/bin/bash
# Test Ollama connection

OLLAMA_HOST="$ollama_host"

echo "Testing Ollama connection..."
echo "Host: \$OLLAMA_HOST"
echo ""

# Test API endpoint
if curl -f -s -m 5 "\$OLLAMA_HOST/api/tags" > /dev/null; then
    echo "✓ Connection successful!"
    echo ""
    echo "Available models:"
    curl -s "\$OLLAMA_HOST/api/tags" | python3 -m json.tool 2>/dev/null | grep -A1 '"name"' | grep -v '^--$' || echo "Could not parse models"
else
    echo "✗ Connection failed!"
    echo "Make sure Ollama is running and accessible at \$OLLAMA_HOST"
    exit 1
fi
EOF

    chmod +x /usr/local/bin/ollama-test
    log_info "Created test script: ollama-test"
}

# Create connection info file
create_connection_info() {
    local gpu_ip="$1"
    local port="$2"
    local ollama_host="$3"

    cat > /opt/ai-platform/ollama-connection.txt << EOF
Ollama Remote Connection Configuration
======================================
Configuration Date: $(date)
GPU Machine IP: $gpu_ip
Ollama Port: $port
Full URL: $ollama_host

Status: Active

To disconnect and use local Ollama:
  sudo $0 localhost

To test connection:
  ollama-test

To use in your projects:
  export OLLAMA_HOST=$ollama_host
  curl $ollama_host/api/tags
EOF

    log_info "Connection info saved to /opt/ai-platform/ollama-connection.txt"
}

# Setup GPU machine instructions
display_gpu_setup_instructions() {
    log_info ""
    log_info "================================================"
    log_info "GPU Machine Setup Instructions"
    log_info "================================================"
    log_info ""
    log_info "On your GPU machine, run the following commands:"
    log_info ""
    log_info "1. Install Ollama (if not installed):"
    log_info "   curl -fsSL https://ollama.com/install.sh | sh"
    log_info ""
    log_info "2. Expose Ollama to network:"
    log_info "   sudo systemctl stop ollama"
    log_info "   echo 'OLLAMA_HOST=0.0.0.0:11434' | sudo tee -a /etc/environment"
    log_info "   sudo systemctl start ollama"
    log_info ""
    log_info "3. Pull some models:"
    log_info "   ollama pull llama3:8b"
    log_info "   ollama pull nomic-embed-text"
    log_info "   ollama pull qwen2.5-coder:7b"
    log_info ""
    log_info "4. Configure firewall (if needed):"
    log_info "   sudo ufw allow 11434/tcp"
    log_info ""
    log_info "5. Verify Ollama is accessible:"
    log_info "   curl http://localhost:11434/api/tags"
    log_info ""
}

# Display connection summary
display_summary() {
    local gpu_ip="$1"
    local port="$2"
    local ollama_host="$3"

    log_info ""
    log_info "================================================"
    log_info "Ollama Remote Connection Configured!"
    log_info "================================================"
    log_info ""
    log_info "Configuration:"
    log_info "  GPU Machine: $gpu_ip"
    log_info "  Port: $port"
    log_info "  Ollama URL: $ollama_host"
    log_info ""
    log_info "Test connection:"
    log_info "  ollama-test"
    log_info ""
    log_info "Use in Python:"
    log_info "  import os"
    log_info "  os.environ['OLLAMA_HOST'] = '$ollama_host'"
    log_info ""
    log_info "Use in shell:"
    log_info "  export OLLAMA_HOST=$ollama_host"
    log_info "  curl \$OLLAMA_HOST/api/tags"
    log_info ""
    log_info "AutoGen configuration:"
    log_info "  llm_config = {"
    log_info "      'config_list': [{"
    log_info "          'model': 'ollama/llama3:8b',"
    log_info "          'base_url': '$ollama_host',"
    log_info "          'api_key': 'ollama'"
    log_info "      }]"
    log_info "  }"
    log_info ""
    log_info "Note: Restart your shell or run 'source ~/.bashrc' for changes to take effect"
}

# Main execution
main() {
    if [ $# -lt 1 ]; then
        usage
    fi

    local gpu_ip="$1"
    local port="${2:-$DEFAULT_PORT}"
    local ollama_host="http://$gpu_ip:$port"

    log_info "Configuring remote Ollama connection"
    log_info "================================================"

    validate_ip "$gpu_ip"

    # If localhost, remove remote configuration
    if [ "$gpu_ip" = "localhost" ] || [ "$gpu_ip" = "127.0.0.1" ]; then
        log_info "Configuring local Ollama (removing remote connection)..."
        ollama_host="http://localhost:11434"
        gpu_ip="localhost"
        port=11434
    fi

    # Test connection first
    if ! test_connection "$gpu_ip" "$port"; then
        log_warn "Connection test failed, but continuing with configuration..."
        log_warn "Make sure to setup the GPU machine properly (see instructions below)"
    fi

    # Configure based on permissions
    if [[ $EUID -eq 0 ]]; then
        configure_system_wide "$ollama_host"
        configure_user_level "$ollama_host"
        create_test_script "$ollama_host"
        create_connection_info "$gpu_ip" "$port" "$ollama_host"
    else
        configure_user_level "$ollama_host"
    fi

    display_summary "$gpu_ip" "$port" "$ollama_host"

    if [ "$gpu_ip" != "localhost" ] && [ "$gpu_ip" != "127.0.0.1" ]; then
        display_gpu_setup_instructions
    fi
}

main "$@"
